### ISSUE TITLE
Scrolling with scroll wheel is backward

### ISSUE THREAD

**Issue by rosshadden** [cfangmeier/tuijam#14]
I noticed you added mouse scrolling in the git logs. Very cool!
For me it's reversed though. When you scroll up it moves the cursor down, and vice versa.

**Comment by cfangmeier** [comment]
Ever since Apple (Any maybe people earlier?) decided to do the "natural" scrolling thing, I've been screwed up on scrolling direction. I'll add a config option so users can reverse it if the other way feels more natural.

**Comment by cfangmeier** [comment]
Alright. As of 8b0a77b, you can reverse the scrolling direction by setting

```yaml
reverse_scrolling: True
```

In the config file.
