### ISSUE TITLE
Play/Pause breaks after pausing the last song in a queue at its end

### ISSUE THREAD

**Issue by t1meshift** [cfangmeier/tuijam#20]
I was going to catch and try to fix issue #10. I paused "Dead" track at its very end (it was the last track in a queue). Pause didn't work, it just finished playing and put the player in weird state. I can add tracks to a queue but I can't play any of them.
![default](https://user-images.githubusercontent.com/7311956/53086227-6fbfb000-3550-11e9-8022-c7f3cb7bc767.png)

**Comment by cfangmeier** [comment]
I'm not surprised that something like this could happen given what I described in #10 . I briefly tried to reproduce this bug, but my fingers aren't quick enough :). Please share if you find a way to reliably invoke the bug, or even better, a fix for it.

**Comment by cfangmeier** [comment]
@t1meshift Can you check out 9003eae and see if that fixes this issue for you?

**Comment by t1meshift** [comment]
Well, at least I can't reproduce it for now. Also I have a tiny pull request which fixes 2 bugs, could you take a look at it? :octocat:
