### ISSUE TITLE
Add a link to the AUR package

### ISSUE THREAD

**Issue by t1meshift** [cfangmeier/tuijam#22]
As the package mentioned in readme file is not maintained regularly, I have decided to submit my own which installs the most fresh version of tuijam straight from this repo. Could you just add it in readme as an alternative to outdated package?

Here it is:
https://aur.archlinux.org/packages/tuijam-git/

**Comment by cfangmeier** [comment]
Thanks!. The git package installs and runs fine on my machine so I'll update the readme accordingly.

**Comment by klardotsh** [comment]
I've been on the road for the past ~two months almost constantly - sorry for not seeing this sooner.

I've orphaned the main package `tuijam` and it's up for grabs by whomever would like it: https://aur.archlinux.org/packages/tuijam/

**Comment by cfangmeier** [comment]
Thanks @klardotsh for putting together the package. I think it makes sense for me to adopt the package so I can update it whenever a new version gets released. I'll see if I can figure out how to adopt a package...
