### ISSUE TITLE
Add Last.fm scrobbling

### ISSUE THREAD

**Issue by t1meshift** [cfangmeier/tuijam#28]
Actually, I could implement it by myself, but it's required to create an API account on Last.fm for this purpose. Since the project is yours, I've decided to write this feature request.

**Comment by cfangmeier** [comment]
I just made an API account for TUIJam. Here are the credentials. Let me know if you need anything else to implement this feature.

![image](https://user-images.githubusercontent.com/2569566/57181662-55615700-6e5c-11e9-819f-5eebbc609873.png)
