### ISSUE TITLE
Crash on HTTP 403 while trying to play a song

### ISSUE THREAD

**Issue by t1meshift** [cfangmeier/tuijam#34]
Google loves removing tracks from GPM regularly. When you try to play removed track that was in a queue, the API returns HTTP 403.
 
I think that the crash is a bit too hardcore way to notify a user that the track is not available now :)

**Comment by cfangmeier** [comment]
Can you post a stack trace of the error you saw so I can see where the error comes from, what the exception is, etc?

**Comment by t1meshift** [comment]
I'm unable to reproduce the crash right now, but I remember that API had returned HTML code with content like `403 Forbidden` or something like that.

**Comment by cfangmeier** [comment]
Should be fixed, provided that the 403 is happening during the `get_stream_url` call. 

5fdcf5a1af64cd87c5ad75c5df202716efc8e008

Note that there is a typo in the commit message, it should say "Fixes #34".
