### ISSUE TITLE
Add a way to view liked songs and playlists

### ISSUE THREAD

**Issue by kiikoh** [cfangmeier/tuijam#46]
I don't think this is currently a feature...

**Comment by cfangmeier** [comment]
Hi @kiikoh, You can do this by entering in an empty search query. Your liked songs will be listed as a playlist at the bottom called "Liked".

**Comment by kiikoh** [comment]
Ok, Thanks, how can I search for radio stations? For example, Today's Dance/EDM Hits.

**Comment by cfangmeier** [comment]
This is not currently supported in tuijam. However, I just had a look through the gmusicapi documentation and it should be possible. I'll make a new issue for this feature.
