### ISSUE TITLE
Use terminal colors instead of hard coded ones. 

### ISSUE THREAD

**Issue by kiikoh** [cfangmeier/tuijam#48]
I want to use this with pywal to complete my rice and this is the last thing I need.

**Comment by cfangmeier** [comment]
0e11f9845b256a3613d935a9e2a9325f4cf66d48 addresses this. You now just add `use_terminal_colors: true` to your tuijam config file. Feel free to reopen if you have any issues with this (and a look at your rice would be cool!).

**Comment by kiikoh** [comment]
Thanks, but now it doesn't honor transparency like it used to, will post pics after.
