### ISSUE TITLE
Add shortcut for clearing the queues and/or selecting multiple songs in the queue

### ISSUE THREAD

**Issue by rkratky** [cfangmeier/tuijam#65]
It would be nice to have the possibility to discard the current queue with a single command (instead of needing to remove individual songs with `Delete`/`x`).

Alternatively, the ability to select multiple songs in the queue (which then be deleted with `Delete`/`x`).

**Comment by cfangmeier** [comment]
There actually is a command for clearing the current queue. By default it is `ctrl w`.

**Comment by rkratky** [comment]
How did I miss that?

Thanks.
