### ISSUE TITLE
Feature Request: Now playing support

### ISSUE THREAD

**Issue by Moovlin** [cfangmeier/tuijam#9]
I'd like to have a "Now Playing" feature similar to that of gpymusic where it just writes to a file such that I can use it with i3 bar. Rather than just making a request I would be interested in implementing it as well. I'm a pretty experienced python programmer but I'm clearly new to the code base so some direction in where would most make sense to add such a feature would be awesome. 

Since I'm only interested in information about the song playing and not the current status would it make the most sense to write a function that writes the song.__repr__() to a file when called in play()? I suppose if one were to be interested in the song data the call would need to happen else where and frankly I'm not sure where that would be. Thanks for any advice on the direction!

**Comment by cfangmeier** [comment]
I think this sounds like a great feature!

What you suggest sounds reasonable, although `repr` may not deliver the song in the best format. That really just comes down to taste though.

If you would like to include status information (ie playing/paused, progress, etc), the place to do that would be `refresh` https://github.com/cfangmeier/tuijam/blob/master/tuijam#L640. This function gets called every 0.5s to update the progress bar, but it could additionally call a method to write out the status to a file.

One more point: I think it would be ideal to be able to specify the file to write to in the YAML config. Then, if it *is* specified in the configuration, write to it, otherwise disable the feature.

How does this sound?

**Comment by Moovlin** [comment]
The config idea sounds like a great idea to me. It may not be a huge deal in terms of performance but do you have any ideas other than putting an if statement in that checks for truth of a boolean each update? This would most definitely be the easiest to implement but easy doesn't mean it's a great solution. My only other thought on a different solution would be to override the existing `refresh` function when instantiating the App class in `main`. This way the check would be done only once when the program loads and then it would simply be a matter of `app.refresh = app.refresh_and_write`. The main issue with this is that it would introduce duplicate code since by changing the reference you lose the objects old refresh function.

If you have any other ideas about a good way to implement this I would be more than happy to hear about them.

**Comment by cfangmeier** [comment]
I think checking on each update is totally fine(premature optimization and all that :) ), Personally, I would save the filename in the App when reading the config and set it to `None` if it's not in the config file. Then in update, just do something like 

```python
if self.status_file is not None:
    # update the status file appropriately
```

**Comment by cfangmeier** [comment]
One other point: It would be good if the first-time setup gave the user an opportunity to enter the path(maybe with a reasonable default, although I couldn't say what that would be). Or at least advertise that they can edit the config file after the fact to enable this feature.

**Comment by cfangmeier** [comment]
@Moovlin are you still interested in implementing this? If not I can take a whack at it myself sometime over the next couple days.

**Comment by Moovlin** [comment]
@cfangmeier I was planning to try and work on it this weekend actually. I was swamped with school work and club stuff this past weekend. You're welcome to work on it but I'm definitely still interested in getting my hands dirty with it.

**Comment by cfangmeier** [comment]
Support for this has recently been added via the MPRIS feature. I'm going to mark this as closed, but feel free to re-open if your use-case is not solved.
